# Lectura de fuentes de datos.
- 120 a√±os de olimpiadas. 
- https://www.kaggle.com/datasets/heesoo37/120-years-of-olympic-history-athletes-and-results

In [1]:
# Importando librrerias
import os
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Consultando arhivos locales en ruta datasets / inputs
path_input_datasets = "../datasets/input/olimpiadas/"
path_output = "../datasets/output/"
os.listdir(path_input_datasets)
#os.mkdir("../datasets/output")

['athlete_events.csv',
 'Forbes Richest Athletes 1990-2020.csv',
 'noc_regions.csv']

In [3]:
olympics = pd.read_csv(path_input_datasets+'athlete_events.csv')
olympics.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

### Realizando Filtros mascaras, query
### Ejemplo para atletas olimpicos peruanos.

In [4]:
olympics[olympics['NOC'] == 'PER']

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
1076,605,Fernando J. Abugattas Aboino,M,20.0,190.0,80.0,Peru,PER,1968 Summer,1968,Summer,Mexico City,Athletics,Athletics Men's High Jump,NaN
1077,606,Roberto Abugattas Aboino,M,21.0,182.0,77.0,Peru,PER,1964 Summer,1964,Summer,Tokyo,Athletics,Athletics Men's High Jump,NaN
1078,606,Roberto Abugattas Aboino,M,25.0,182.0,77.0,Peru,PER,1968 Summer,1968,Summer,Mexico City,Athletics,Athletics Men's High Jump,NaN
1166,649,Fernando Acevedo Portugues,M,22.0,175.0,65.0,Peru,PER,1968 Summer,1968,Summer,Mexico City,Athletics,Athletics Men's 200 metres,NaN
1167,649,Fernando Acevedo Portugues,M,26.0,175.0,65.0,Peru,PER,1972 Summer,1972,Summer,Munich,Athletics,Athletics Men's 400 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267568,133860,Miguel Zambrano de la Cruz,M,28.0,182.0,148.0,Peru,PER,1980 Summer,1980,Summer,Moskva,Wrestling,"Wrestling Men's Super-Heavyweight, Freestyle",NaN
267640,133894,Yulissa Noelia Zamudio Orl,F,20.0,185.0,75.0,Peru,PER,1996 Summer,1996,Summer,Atlanta,Volleyball,Volleyball Women's Volleyball,NaN
267641,133894,Yulissa Noelia Zamudio Orl,F,24.0,185.0,75.0,Peru,PER,2000 Summer,2000,Summer,Sydney,Volleyball,Volleyball Women's Volleyball,NaN
268048,134100,Ramn Zavaleta,M,24.0,181.0,72.0,Peru,PER,1984 Summer,1984,Summer,Los Angeles,Cycling,"Cycling Men's Road Race, Individual",NaN
268270,134227,Carlos Erick Zegarra Presser,M,23.0,202.0,165.0,Peru,PER,2008 Summer,2008,Summer,Beijing,Judo,Judo Men's Heavyweight,NaN

In [6]:
olympics.query('NOC == "PER"')

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
1076,605,Fernando J. Abugattas Aboino,M,20.0,190.0,80.0,Peru,PER,1968 Summer,1968,Summer,Mexico City,Athletics,Athletics Men's High Jump,NaN
1077,606,Roberto Abugattas Aboino,M,21.0,182.0,77.0,Peru,PER,1964 Summer,1964,Summer,Tokyo,Athletics,Athletics Men's High Jump,NaN
1078,606,Roberto Abugattas Aboino,M,25.0,182.0,77.0,Peru,PER,1968 Summer,1968,Summer,Mexico City,Athletics,Athletics Men's High Jump,NaN
1166,649,Fernando Acevedo Portugues,M,22.0,175.0,65.0,Peru,PER,1968 Summer,1968,Summer,Mexico City,Athletics,Athletics Men's 200 metres,NaN
1167,649,Fernando Acevedo Portugues,M,26.0,175.0,65.0,Peru,PER,1972 Summer,1972,Summer,Munich,Athletics,Athletics Men's 400 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267568,133860,Miguel Zambrano de la Cruz,M,28.0,182.0,148.0,Peru,PER,1980 Summer,1980,Summer,Moskva,Wrestling,"Wrestling Men's Super-Heavyweight, Freestyle",NaN
267640,133894,Yulissa Noelia Zamudio Orl,F,20.0,185.0,75.0,Peru,PER,1996 Summer,1996,Summer,Atlanta,Volleyball,Volleyball Women's Volleyball,NaN
267641,133894,Yulissa Noelia Zamudio Orl,F,24.0,185.0,75.0,Peru,PER,2000 Summer,2000,Summer,Sydney,Volleyball,Volleyball Women's Volleyball,NaN
268048,134100,Ramn Zavaleta,M,24.0,181.0,72.0,Peru,PER,1984 Summer,1984,Summer,Los Angeles,Cycling,"Cycling Men's Road Race, Individual",NaN
268270,134227,Carlos Erick Zegarra Presser,M,23.0,202.0,165.0,Peru,PER,2008 Summer,2008,Summer,Beijing,Judo,Judo Men's Heavyweight,NaN

In [7]:
# Realizando filtros conjuntos, Ejemplo los medallistas de Seul 88.
olympics[(olympics['NOC'] == 'PER') & 
         (olympics['Sport'] == 'Volleyball') & 
         (olympics['Year'] == 1988) & 
         (olympics['Medal'] == 'Silver')]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
37847,19448,Luisa Haydee Cervera Cevedon,F,24.0,173.0,70.0,Peru,PER,1988 Summer,1988,Summer,Seoul,Volleyball,Volleyball Women's Volleyball,Silver
51127,26272,Alejandra de la Guerra,F,20.0,173.0,59.0,Peru,PER,1988 Summer,1988,Summer,Seoul,Volleyball,Volleyball Women's Volleyball,Silver
66098,33819,Denisse Fajardo Garca,F,24.0,171.0,62.0,Peru,PER,1988 Summer,1988,Summer,Seoul,Volleyball,Volleyball Women's Volleyball,Silver
75122,38118,Miriam Gallardo,F,20.0,168.0,57.0,Peru,PER,1988 Summer,1988,Summer,Seoul,Volleyball,Volleyball Women's Volleyball,Silver
76249,38692,Rosa Gisella Garca Rivas,F,24.0,175.0,69.0,Peru,PER,1988 Summer,1988,Summer,Seoul,Volleyball,Volleyball Women's Volleyball,Silver
94622,47883,Sonia Isabel Heredia,F,24.0,175.0,69.0,Peru,PER,1988 Summer,1988,Summer,Seoul,Volleyball,Volleyball Women's Volleyball,Silver
98804,50004,"Katherine ""Kathy"" Horny",F,18.0,186.0,76.0,Peru,PER,1988 Summer,1988,Summer,Seoul,Volleyball,Volleyball Women's Volleyball,Silver
147339,73946,Natalia Mara Mlaga Dibos,F,24.0,170.0,59.0,Peru,PER,1988 Summer,1988,Summer,Seoul,Volleyball,Volleyball Women's Volleyball,Silver
185611,93317,"Gabriela Lourdes ""Gaby"" Prez del Solar Cuculiza",F,20.0,194.0,72.0,Peru,PER,1988 Summer,1988,Summer,Seoul,Volleyball,Volleyball Women's Volleyball,Silver
234999,117844,Cecilia Roxana Tait Villacorta,F,26.0,182.0,70.0,Peru,PER,1988 Summer,1988,Summer,Seoul,Volleyball,Volleyball Women's Volleyball,Silver
242031,121233,Gina Torrealva,F,26.0,175.0,59.0,Peru,PER,1988 Summer,1988,Summer,Seoul,Volleyball,Volleyball Women's Volleyball,Silver
246625,123484,Cenaida Cebastiana Uribe Medina,F,22.0,174.0,65.0,Peru,PER,1988 Summer,1988,Summer,Seoul,Volleyball,Volleyball Women's Volleyball,Silver

In [8]:
# Realizando filtros conjuntos, Ejemplo los medallistas de Seul 88 con la funcion query.
olympics.query('(NOC == "PER") & (Sport == "Volleyball") & (Year == 1988) & (Medal == "Silver")')

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
37847,19448,Luisa Haydee Cervera Cevedon,F,24.0,173.0,70.0,Peru,PER,1988 Summer,1988,Summer,Seoul,Volleyball,Volleyball Women's Volleyball,Silver
51127,26272,Alejandra de la Guerra,F,20.0,173.0,59.0,Peru,PER,1988 Summer,1988,Summer,Seoul,Volleyball,Volleyball Women's Volleyball,Silver
66098,33819,Denisse Fajardo Garca,F,24.0,171.0,62.0,Peru,PER,1988 Summer,1988,Summer,Seoul,Volleyball,Volleyball Women's Volleyball,Silver
75122,38118,Miriam Gallardo,F,20.0,168.0,57.0,Peru,PER,1988 Summer,1988,Summer,Seoul,Volleyball,Volleyball Women's Volleyball,Silver
76249,38692,Rosa Gisella Garca Rivas,F,24.0,175.0,69.0,Peru,PER,1988 Summer,1988,Summer,Seoul,Volleyball,Volleyball Women's Volleyball,Silver
94622,47883,Sonia Isabel Heredia,F,24.0,175.0,69.0,Peru,PER,1988 Summer,1988,Summer,Seoul,Volleyball,Volleyball Women's Volleyball,Silver
98804,50004,"Katherine ""Kathy"" Horny",F,18.0,186.0,76.0,Peru,PER,1988 Summer,1988,Summer,Seoul,Volleyball,Volleyball Women's Volleyball,Silver
147339,73946,Natalia Mara Mlaga Dibos,F,24.0,170.0,59.0,Peru,PER,1988 Summer,1988,Summer,Seoul,Volleyball,Volleyball Women's Volleyball,Silver
185611,93317,"Gabriela Lourdes ""Gaby"" Prez del Solar Cuculiza",F,20.0,194.0,72.0,Peru,PER,1988 Summer,1988,Summer,Seoul,Volleyball,Volleyball Women's Volleyball,Silver
234999,117844,Cecilia Roxana Tait Villacorta,F,26.0,182.0,70.0,Peru,PER,1988 Summer,1988,Summer,Seoul,Volleyball,Volleyball Women's Volleyball,Silver
242031,121233,Gina Torrealva,F,26.0,175.0,59.0,Peru,PER,1988 Summer,1988,Summer,Seoul,Volleyball,Volleyball Women's Volleyball,Silver
246625,123484,Cenaida Cebastiana Uribe Medina,F,22.0,174.0,65.0,Peru,PER,1988 Summer,1988,Summer,Seoul,Volleyball,Volleyball Women's Volleyball,Silver